#ifndef __GAMELEVELMANAGER_H__
#define __GAMELEVELMANAGER_H__


#include "../includes.h"

class GameLevelManager: public cocos2d::CCNode {
public:
    static GameLevelManager* sharedState();
    static GameLevelManager* get();
    void acceptFriendRequest(int p0, int p1);
    int accountIDForUserID(int userID);
    void addDLToActive(char const* p0);
    bool areGauntletsLoaded();
    void banUser(int p0);
    void blockUser(int p0);
    void cleanupDailyLevels();
    bool createAndGetAccountComments(std::string p0, int p1);
    bool createAndGetCommentsFull(std::string p0, int p1, bool p2);
    bool createAndGetLevelComments(std::string p0, int p1);
    cocos2d::CCArray* createAndGetLevelLists(std::string p0);
    cocos2d::CCArray* createAndGetLevels(std::string p0);
    cocos2d::CCArray* createAndGetMapPacks(std::string p0);
    cocos2d::CCArray* createAndGetScores(std::string p0, GJScoreType p1);
    GJGameLevel* createNewLevel();
    GJLevelList* createNewLevelList();
    TodoReturn createPageInfo(int p0, int p1, int p2);
    GJSmartTemplate* createSmartTemplate();
    void dataLoaded(DS_Dictionary* p0);
    void deleteAccountComment(int p0, int p1);
    void deleteComment(int p0, CommentType p1, int p2);
    void deleteFriendRequests(int p0, cocos2d::CCArray* p1, bool p2);
    void deleteLevel(GJGameLevel* p0);
    void deleteLevelComment(int p0, int p1);
    void deleteLevelList(GJLevelList* p0);
    void deleteSentFriendRequest(int p0);
    void deleteServerLevel(int p0);
    void deleteServerLevelList(int p0);
    void deleteSmartTemplate(GJSmartTemplate* p0);
    void deleteUserMessages(GJUserMessage* message, cocos2d::CCArray* messages, bool isSender);
    void downloadLevel(int p0, bool p1);
    void downloadUserMessage(int p0, bool p1);
    void encodeDataTo(DS_Dictionary* p0);
    void firstSetup();
    void followUser(int p0);
    GJFriendRequest* friendRequestFromAccountID(int p0);
    void friendRequestWasRemoved(int p0, bool p1);
    char const* getAccountCommentKey(int p0, int p1);
    void getAccountComments(int accountID, int page, int total);
    int getActiveDailyID(GJTimedLevelType p0);
    GJSmartTemplate* getActiveSmartTemplate();
    cocos2d::CCArray* getAllSmartTemplates();
    cocos2d::CCDictionary* getAllUsedSongIDs();
    gd::string getBasePostString();
    bool getBoolForKey(char const* p0);
    gd::string getCommentKey(int ID, int page, int mode, CommentKeyType keytype);
    cocos2d::CCArray* getCompletedLevels(bool p0);
    int getDailyID(GJTimedLevelType p0);
    double getDailyTimer(GJTimedLevelType p0);
    char const* getDeleteCommentKey(int p0, int p1, int p2);
    char const* getDeleteMessageKey(int p0, bool p1);
    char const* getDescKey(int p0);
    gd::string getActiveDailyID(bool p0, bool p1, bool p2, bool p3, bool p4, bool p5, bool p6, bool p7);
    char const* getDiffKey(int p0);
    bool getDiffVal(int p0);
    gd::string getFolderName(int p0, bool p1);
    char const* getFriendRequestKey(bool p0, int p1);
    void getFriendRequests(bool p0, int p1, int p2);
    char const* getGauntletKey(int p0);
    void getGauntletLevels(int p0);
    void getGauntlets();
    void getGauntletsearchKey(int p0);
    void getGJChallenges();
    void getGJDailyLevelState(GJTimedLevelType p0);
    void getGJRewards(int p0);
    void getGJUserInfo(int p0);
    int getHighestLevelOrder();
    int getIntForKey(char const* p0);
    void getLeaderboardScores(char const* p0);
    gd::string getLengthStr(bool p0, bool p1, bool p2, bool p3, bool p4, bool p5);
    const char * getLenKey(int len);
    bool getLenVal(int p0);
    void getLevelComments(int ID, int page, int total, int mode, CommentKeyType keytype);
    const char* getLevelDownloadKey(int levelID, bool isGauntlet);
    const char* getLevelKey(int levelID);
    void getLevelLeaderboard(GJGameLevel* p0, LevelLeaderboardType p1, LevelLeaderboardMode p2);
    char const* getLevelLeaderboardKey(int p0, LevelLeaderboardType p1, LevelLeaderboardMode p2);
    char const* getLevelListKey(int p0);
    void getLevelLists(GJSearchObject* p0);
    void getLevelSaveData();
    char const* getLikeAccountItemKey(LikeItemType p0, int p1, bool p2, int p3);
    char const* getLikeItemKey(LikeItemType p0, int p1, bool p2, int p3);
    GJGameLevel* getLocalLevel(int p0);
    GJGameLevel* getLocalLevelByName(std::string p0);
    GJLevelList* getAllUsedSongIDs(int p0);
    int getLowestLevelOrder();
    GJGameLevel* getMainLevel(int p0, bool p1);
    const char* getMapPackKey(int pack);
    void getMapPacks(GJSearchObject* p0);
    char const* getMessageKey(int p0);
    char const* getMessagesKey(bool p0, int p1);
    void getNews();
    int getNextFreeTemplateID();
    gd::string getNextLevelName(std::string p0);
    void getOnlineLevels(GJSearchObject* p0);
    char const* getPageInfo(char const* p0);
    char const* getPostCommentKey(int p0);
    const char * getRateStarsKey(int key);
    char const* getReportKey(int p0);
    GJGameLevel* getSavedDailyLevel(int p0);
    GJGameLevel* getSavedDailyLevelFromLevelID(int p0);
    GJGameLevel* getSavedGauntlet(int p0);
    GJGameLevel* getSavedGauntletLevel(int p0);
    GJGameLevel* getSavedLevel(GJGameLevel* p0);
    GJGameLevel* getSavedLevel(int p0);
    GJLevelList* getSavedLevelList(int p0);
    cocos2d::CCArray* getSavedLevelLists(int p0);
    cocos2d::CCArray* getSavedLevels(bool p0, int p1);
    TodoReturn getSavedMapPack(int p0);
    cocos2d::CCScene* getSearchScene(char const* p0);
    int getSplitIntFromKey(char const* p0, int p1);
    TodoReturn getStoredLevelComments(char const* p0);
    cocos2d::CCArray* getStoredOnlineLevels(char const* p0);
    cocos2d::CCArray* getStoredUserList(UserListType p0);
    GJUserMessage* getStoredUserMessage(int p0);
    GJUserMessage* getStoredUserMessageReply(int p0);
    double getTimeLeft(char const* p0, float p1);
    void getTopArtists(int page, int total);
    const char* getTopArtistsKey(int page);
    char const* getUploadMessageKey(int p0);
    char const* getUserInfoKey(int p0);
    void getUserList(UserListType p0);
    void getUserMessages(bool p0, int p1, int p2);
    void getUsers(GJSearchObject* p0);
    void gotoLevelPage(GJGameLevel* p0);
    void handleIt(bool p0, std::string p1, std::string p2, GJHttpType p3);
    void handleItDelayed(bool p0, std::string p1, std::string p2, GJHttpType p3);
    void handleItND(cocos2d::CCNode* p0, void* p1);
    bool hasDailyStateBeenLoaded(GJTimedLevelType p0);
    bool hasDownloadedLevel(int p0);
    bool hasDownloadedList(int p0);
    bool hasLikedAccountItem(LikeItemType p0, int p1, bool p2, int p3);
    bool hasLikedItem(LikeItemType p0, int p1, bool p2, int p3);
    bool hasLikedItemFullCheck(LikeItemType p0, int p1, int p2);
    bool hasRatedDemon(int p0);
    bool hasRatedLevelStars(int p0);
    bool hasReportedLevel(int p0);
    void invalidateMessages(bool p0, bool p1);
    void invalidateRequests(bool p0, bool p1);
    void invalidateUserList(UserListType p0, bool p1);
    bool isDLActive(char const* tag);
    bool isFollowingUser(int p0);
    bool isTimeValid(char const* p0, float p1);
    bool isUpdateValid(int p0);
    int itemIDFromLikeKey(char const* p0);
    bool keyHasTimer(char const* p0);
    int levelIDFromCommentKey(char const* p0);
    int levelIDFromPostCommentKey(char const* p0);
    int likeFromLikeKey(char const* p0);
    void likeItem(LikeItemType p0, int p1, bool p2, int p3);
    void limitSavedLevels();
    void makeTimeStamp(char const* p0);
    void markItemAsLiked(LikeItemType p0, int p1, bool p2, int p3);
    void markLevelAsDownloaded(int p0);
    void markLevelAsRatedDemon(int p0);
    void markLevelAsRatedStars(int p0);
    void markLevelAsReported(int p0);
    void markListAsDownloaded(int id);
    void messageWasRemoved(int p0, bool p1);
    void onAcceptFriendRequestCompleted(std::string response, std::string tag);
    void onBanUserCompleted(std::string response, std::string tag);
    void onBlockUserCompleted(std::string response, std::string tag);
    void onDeleteCommentCompleted(std::string response, std::string tag);
    void onDeleteFriendRequestCompleted(std::string response, std::string tag);
    void onDeleteServerLevelCompleted(std::string response, std::string tag);
    void onDeleteServerLevelListCompleted(std::string response, std::string tag);
    void onDeleteUserMessagesCompleted(std::string response, std::string tag);
    void onDownloadLevelCompleted(std::string response, std::string tag);
    void onDownloadUserMessageCompleted(std::string response, std::string tag);
    void onGetAccountCommentsCompleted(std::string response, std::string tag);
    void onGetFriendRequestsCompleted(std::string response, std::string tag);
    void onGetGauntletsCompleted(std::string response, std::string tag);
    void onGetGJChallengesCompleted(std::string response, std::string tag);
    void onGetGJDailyLevelStateCompleted(std::string response, std::string tag);
    void onGetGJRewardsCompleted(std::string response, std::string tag);
    void onGetGJUserInfoCompleted(std::string response, std::string tag);
    void onGetLeaderboardScoresCompleted(std::string response, std::string tag);
    void onGetLevelCommentsCompleted(std::string response, std::string tag);
    void onGetLevelLeaderboardCompleted(std::string response, std::string tag);
    void onGetLevelListsCompleted(std::string response, std::string tag);
    void onGetLevelSaveDataCompleted(std::string response, std::string tag);
    void onGetMapPacksCompleted(std::string response, std::string tag);
    void onGetNewsCompleted(std::string response, std::string tag);
    void onGetOnlineLevelsCompleted(std::string response, std::string tag);
    void onGetTopArtistsCompleted(std::string response, std::string tag);
    void onGetUserListCompleted(std::string response, std::string tag);
    void onGetUserMessagesCompleted(std::string response, std::string tag);
    void onGetUsersCompleted(std::string response, std::string tag);
    void onLikeItemCompleted(std::string response, std::string tag);
    void onProcessHttpRequestCompleted(cocos2d::extension::CCHttpClient* p0, cocos2d::extension::CCHttpResponse* p1);
    void onRateDemonCompleted(std::string response, std::string tag);
    void onRateStarsCompleted(std::string response, std::string tag);
    void onReadFriendRequestCompleted(std::string response, std::string tag);
    void onRemoveFriendCompleted(std::string response, std::string tag);
    void onReportLevelCompleted(std::string response, std::string tag);
    void onRequestUserAccessCompleted(std::string response, std::string tag);
    void onRestoreItemsCompleted(std::string response, std::string tag);
    void onSetLevelFeaturedCompleted(std::string response, std::string tag);
    void onSetLevelStarsCompleted(std::string response, std::string tag);
    void onSubmitUserInfoCompleted(std::string response, std::string tag);
    void onSuggestLevelStarsCompleted(std::string response, std::string tag);
    void onUnblockUserCompleted(std::string response, std::string tag);
    void onUpdateDescriptionCompleted(std::string response, std::string tag);
    void onUpdateLevelCompleted(std::string response, std::string tag);
    void onUpdateUserScoreCompleted(std::string response, std::string tag);
    void onUploadCommentCompleted(std::string response, std::string tag);
    void onUploadFriendRequestCompleted(std::string response, std::string tag);
    void onUploadLevelCompleted(std::string response, std::string tag);
    void onUploadLevelListCompleted(std::string response, std::string tag);
    void onUploadUserMessageCompleted(std::string response, std::string tag);
    int pageFromCommentKey(char const* p0);
    void parseRestoreData(std::string p0);
    void performNetworkTest();
    void ProcessHttpRequest(std::string endpoint, std::string params, std::string tag, GJHttpType httpType);
    void processOnDownloadLevelCompleted(std::string p0, std::string p1, bool p2);
    void purgeUnusedLevels();
    void rateDemon(int p0, int p1, bool p2);
    void rateStars(int p0, int p1);
    void readFriendRequest(int p0);
    TodoReturn removeDelimiterChars(std::string p0, bool p1);
    void removeDLFromActive(char const* p0);
    void removeFriend(int p0);
    void removeLevelDownloadedKeysFromDict(cocos2d::CCDictionary* p0);
    void removeUserFromList(int p0, UserListType p1);
    void reportLevel(int p0);
    void requestUserAccess();
    void resetAccountComments(int p0);
    void resetAllTimers();
    void resetCommentTimersForLevelID(int p0, CommentKeyType p1);
    void resetDailyLevelState(GJTimedLevelType p0);
    void resetGauntlets();
    void resetStoredUserList(UserListType p0);
    void resetTimerForKey(char const* p0);
    static cocos2d::CCDictionary* responseToDict(std::string p0, bool p1);
    void restoreItems();
    void saveFetchedLevelLists(cocos2d::CCArray* p0);
    void saveFetchedLevels(cocos2d::CCArray* p0);
    void saveFetchedMapPacks(cocos2d::CCArray* p0);
    void saveGauntlet(GJMapPack* p0);
    void saveLevel(GJGameLevel* p0);
    void saveLevelList(GJLevelList* p0);
    void saveLocalScore(int p0, int p1, int p2);
    void saveMapPack(GJMapPack* p0);
    void setActiveSmartTemplate(GJSmartTemplate* p0);
    void setBoolForKey(bool p0, char const* p1);
    void setDiffVal(int p0, bool p1);
    void setFolderName(int p0, std::string p1, bool p2);
    void setIntForKey(int p0, char const* p1);
    void setLenVal(int p0, bool p1);
    void setLevelFeatured(int p0, int p1, bool p2);
    void setLevelStars(int p0, int p1, bool p2);
    int specialFromLikeKey(char const* p0);
    void storeCommentsResult(cocos2d::CCArray* p0, std::string p1, char const* p2);
    void storeDailyLevelState(int p0, int p1, GJTimedLevelType p2);
    void storeFriendRequest(GJFriendRequest* p0);
    void storeSearchResult(cocos2d::CCArray* levels, std::string pageInfo, char const* searchKey);
    void storeUserInfo(GJUserScore* p0);
    void storeUserMessage(GJUserMessage* p0);
    void storeUserMessageReply(int p0, GJUserMessage* p1);
    void storeUserName(int userID, int accountID, std::string userName);
    void storeUserNames(std::string usernameString);
    void submitUserInfo();
    void suggestLevelStars(int p0, int p1, int p2);
    gd::string tryGetUsername(int p0);
    CommentType typeFromCommentKey(char const* p0);
    LikeItemType typeFromLikeKey(char const* p0);
    void unblockUser(int p0);
    void unfollowUser(int p0);
    void updateDescription(int p0, std::string p1);
    void updateLevel(GJGameLevel* p0);
    void updateLevelOrders();
    void updateLevelRewards(GJGameLevel* p0);
    void updateSavedLevelList(GJLevelList* p0);
    void updateUsernames();
    void updateUserScore();
    void uploadAccountComment(std::string p0);
    void uploadComment(std::string p0, CommentType p1, int p2, int p3);
    void uploadFriendRequest(int p0, std::string p1);
    void uploadLevel(GJGameLevel* p0);
    void uploadLevelComment(int p0, std::string p1, int p2);
    void uploadLevelList(GJLevelList* p0);
    void uploadUserMessage(int p0, std::string p1, std::string p2);
    int userIDForAccountID(int p0);
    GJUserScore* userInfoForAccountID(int p0);
    gd::string userNameForUserID(int p0);
    void verifyLevelState(GJGameLevel* p0);
    gd::string writeSpecialFilters(GJSearchObject* p0);
    virtual bool init();
    /* PAD */

    cocos2d::CCDictionary* m_mainLevels;
    cocos2d::CCDictionary* m_searchFilters;
    cocos2d::CCDictionary* m_onlineLevels;
    cocos2d::CCDictionary* m_unkDict;
    cocos2d::CCDictionary* m_followedCreators;
    cocos2d::CCDictionary* m_GLM21;
    cocos2d::CCDictionary* m_downloadedLevels;
    cocos2d::CCDictionary* m_likedLevels;
    cocos2d::CCDictionary* m_ratedLevels;
    cocos2d::CCDictionary* m_ratedDemons;
    cocos2d::CCDictionary* m_reportedLevels;
    cocos2d::CCDictionary* m_onlineFolders;
    cocos2d::CCDictionary* m_localLevelsFolders;
    cocos2d::CCDictionary* m_dailyLevels;
    int m_dailyTimeLeft;
    int m_dailyID;
    int m_dailyIDUnk;
    int m_weeklyTimeLeft;
    int m_weeklyID;
    int m_weeklyIDUnk;
    int m_eventTimeLeft;
    int m_eventID;
    int m_eventIDUnk;
    cocos2d::CCDictionary* m_gauntletLevels;
    std::map<std::string, bool> m_availableFilters;
    cocos2d::CCDictionary* m_timerDict;
    cocos2d::CCDictionary* m_knownUsers;
    cocos2d::CCDictionary* m_accountIDtoUserIDDict;
    cocos2d::CCDictionary* m_userIDtoAccountIDDict;
    cocos2d::CCDictionary* m_storedLevels;
    cocos2d::CCDictionary* m_pageInfo;
    cocos2d::CCDictionary* m_unkDict20;
    cocos2d::CCDictionary* m_savedPacks;
    cocos2d::CCDictionary* m_savedGauntlets;
    cocos2d::CCDictionary* m_downloadObjects;
    cocos2d::CCDictionary* m_friendReqAndUserBlocks;
    cocos2d::CCDictionary* m_storedUserInfo;
    cocos2d::CCDictionary* m_friendRequests;
    cocos2d::CCDictionary* m_userMessages;
    cocos2d::CCDictionary* m_userReplies;
    std::string m_searchSceneStr;
    std::string m_searchType9Str;
    LeaderboardState m_leaderboardState;
    bool m_unkEditLevelLayerOnBack;
    LevelManagerDelegate* m_levelManagerDelegate;
    LevelDownloadDelegate* m_levelDownloadDelegate;
    LevelCommentDelegate* m_levelCommentDelegate;
    CommentUploadDelegate* m_commentUploadDelegate;
    LevelUploadDelegate* m_levelUploadDelegate;
    ListUploadDelegate* m_listUploadDelegate;
    LevelUpdateDelegate* m_levelUpdateDelegate;
    LeaderboardManagerDelegate* m_leaderboardManagerDelegate;
    LevelDeleteDelegate* m_levelDeleteDelegate;
    LevelListDeleteDelegate* m_levelListDeleteDelegate;
    UserInfoDelegate* m_userInfoDelegate;
    void* m_unkDelegate;
    UserListDelegate* m_userListDelegate;
    FriendRequestDelegate* m_friendRequestDelegate;
    MessageListDelegate* m_messageListDelegate;
    DownloadMessageDelegate* m_downloadMessageDelegate;
    UploadMessageDelegate* m_uploadMessageDelegate;
    GJRewardDelegate* m_GJRewardDelegate;
    GJChallengeDelegate* m_GJChallengeDelegate;
    GJDailyLevelDelegate* m_GJDailyLevelDelegate;
    OnlineListDelegate* m_onlineListDelegate;
    int m_unkDownload;
    /* PAD */

    std::string m_unkStr3;
    cocos2d::CCString* m_unkStr4;
};

#endif /* __GAMELEVELMANAGER_H__ */