#ifndef __GJGAMESTATE_H__
#define __GJGAMESTATE_H__


#include "../includes.h"

class GJGameState {
public:
    TodoReturn controlTweenAction(int p0, int p1, GJActionCommand p2);
    TodoReturn getGameObjectPhysics(GameObject* p0);
    TodoReturn processStateTriggers();
    void stopTweenAction(int p0);
    TodoReturn tweenValue(float p0, float p1, int p2, float p3, int p4, float p5, int p6, int p7);
    TodoReturn updateTweenAction(float p0, int p1);
    TodoReturn updateTweenActions(float p0);
    float m_cameraZoom;
    float m_targetCameraZoom;
    cocos2d::CCPoint m_cameraOffset;
    cocos2d::CCPoint m_unkPoint1;
    cocos2d::CCPoint m_unkPoint2;
    cocos2d::CCPoint m_unkPoint3;
    cocos2d::CCPoint m_unkPoint4;
    cocos2d::CCPoint m_unkPoint5;
    cocos2d::CCPoint m_unkPoint6;
    cocos2d::CCPoint m_unkPoint7;
    cocos2d::CCPoint m_unkPoint8;
    cocos2d::CCPoint m_unkPoint9;
    cocos2d::CCPoint m_unkPoint10;
    cocos2d::CCPoint m_unkPoint11;
    cocos2d::CCPoint m_unkPoint12;
    cocos2d::CCPoint m_unkPoint13;
    cocos2d::CCPoint m_unkPoint14;
    cocos2d::CCPoint m_unkPoint15;
    cocos2d::CCPoint m_unkPoint16;
    cocos2d::CCPoint m_unkPoint17;
    cocos2d::CCPoint m_unkPoint18;
    cocos2d::CCPoint m_unkPoint19;
    cocos2d::CCPoint m_unkPoint20;
    cocos2d::CCPoint m_unkPoint21;
    cocos2d::CCPoint m_unkPoint22;
    cocos2d::CCPoint m_unkPoint23;
    cocos2d::CCPoint m_unkPoint24;
    cocos2d::CCPoint m_unkPoint25;
    cocos2d::CCPoint m_unkPoint26;
    cocos2d::CCPoint m_unkPoint27;
    cocos2d::CCPoint m_unkPoint28;
    cocos2d::CCPoint m_unkPoint29;
    bool m_unkBool1;
    int m_unkInt1;
    bool m_unkBool2;
    int m_unkInt2;
    bool m_unkBool3;
    cocos2d::CCPoint m_unkPoint30;
    float m_middleGroundOffsetY;
    int m_unkInt3;
    int m_unkInt4;
    short m_unkShort1;
    float m_unkFloat2;
    float m_unkFloat3;
    int m_unkInt5;
    int m_unkInt6;
    int m_unkInt7;
    int m_unkInt8;
    int m_unkInt9;
    int m_unkInt10;
    int m_unkInt11;
    float m_unkFloat4;
    unsigned int m_unkUint1;
    float m_portalY;
    bool m_unkBool4;
    bool m_gravityRelated;
    int m_unkInt12;
    int m_unkInt13;
    int m_unkInt14;
    int m_unkInt15;
    short m_unkShort2;
    bool m_unkBool5;
    bool m_unkBool6;
    float m_unkFloat5;
    float m_unkFloat6;
    float m_unkFloat7;
    float m_unkFloat8;
    float m_cameraAngle;
    float m_targetCameraAngle;
    bool m_unk184;
    float m_timeWarp;
    float m_timeWarpRelated;
    int m_currentChannel;
    int m_unkInt17;
    std::unordered_map<int, int> m_spawnChannelRelated0;
    std::unordered_map<int, bool> m_spawnChannelRelated1;
    double m_unkDouble1;
    double m_unkDouble2;
    double m_unkDouble3;
    unsigned int m_unkUint2;
    unsigned int m_unkUint3;
    int m_unk1f8;
    unsigned int m_unkUint4;
    unsigned int m_unkUint5;
    unsigned int m_unkUint6;
    unsigned int m_unkUint7;
    GameObject* m_unkGameObjPtr1;
    GameObject* m_unkGameObjPtr2;
    cocos2d::CCPoint m_cameraPosition;
    bool m_unkBool8;
    bool m_unkBool9;
    bool m_unkBool10;
    bool m_unkBool11;
    bool m_unkBool12;
    bool m_unkBool13;
    bool m_unkBool14;
    bool m_unkBool15;
    bool m_unkBool16;
    bool m_unkBool17;
    bool m_isDualMode;
    bool m_unkBool18;
    float m_unkFloat9;
    std::unordered_map<int, GJValueTween> m_tweenActions;
    int m_cameraEdgeValue0;
    int m_cameraEdgeValue1;
    int m_cameraEdgeValue2;
    int m_cameraEdgeValue3;
    std::unordered_map<int, GameObjectPhysics> m_gameObjectPhysics;
    std::vector<float> m_unkVecFloat1;
    unsigned int m_unkUint10;
    unsigned int m_unkUint11;
    unsigned int m_unkUint12;
    cocos2d::CCPoint m_unkPoint31;
    float m_unkFloat10;
    unsigned int m_timeModRelated;
    bool m_timeModRelated2;
    std::map<std::pair<int, int>, int> m_unkMapPairIntIntInt;
    unsigned int m_unkUint13;
    cocos2d::CCPoint m_unkPoint32;
    cocos2d::CCPoint m_unkPoint33;
    bool m_unkBool19;
    bool m_unkBool20;
    bool m_unkBool21;
    bool m_unkBool22;
    bool m_unkBool23;
    bool m_unkBool24;
    unsigned int m_unkUint14;
    bool m_unkBool25;
    bool m_cameraShakeEnabled;
    float m_cameraShakeFactor;
    unsigned int m_unkUint15;
    unsigned int m_unkUint16;
    uint64_t m_unkUint64_1;
    cocos2d::CCPoint m_unkPoint34;
    unsigned int dualRelated;
    std::unordered_map<int, EnhancedGameObject*> m_stateObjects;
    std::map<std::pair<GJGameEvent, int>, std::vector<EventTriggerInstance>> m_unkMapPairGJGameEventIntVectorEventTriggerInstance;
    std::map<std::pair<GJGameEvent, int>, int> m_unkMapPairGJGameEventIntInt;
    std::unordered_map<int, std::vector<EnterEffectInstance>> m_unorderedMapEnterEffectInstanceVectors1;
    std::unordered_map<int, std::vector<EnterEffectInstance>> m_unorderedMapEnterEffectInstanceVectors2;
    std::vector<int> m_unkVecInt1;
    std::vector<int> m_unkVecInt2;
    std::vector<EnterEffectInstance> m_enterEffectInstances1;
    std::vector<EnterEffectInstance> m_enterEffectInstances2;
    std::vector<EnterEffectInstance> m_enterEffectInstances3;
    std::vector<EnterEffectInstance> m_enterEffectInstances4;
    std::vector<EnterEffectInstance> m_enterEffectInstances5;
    std::unordered_set<int> m_unkUnorderedSet1;
    bool m_unkBool26;
    std::vector<AdvancedFollowInstance> m_advanceFollowInstances;
    std::vector<DynamicObjectAction> m_dynamicObjActions1;
    std::vector<DynamicObjectAction> m_dynamicObjActions2;
    bool m_unkBool27;
    bool m_unkBool28;
    unsigned int m_unkUint17;
    std::unordered_map<int, std::vector<int>> unkUMap8;
    std::map<std::pair<int,int>, SFXTriggerInstance> proximityVolumeRelated;
    std::unordered_map<int, SongChannelState> m_songChannelStates;
    std::unordered_map<int, std::vector<SongTriggerState>> m_songTriggerStateVectors;
    std::vector<SFXTriggerState> m_sfxTriggerStates;
    bool m_unkBool29;
    unsigned int m_unkUint18;
    int m_ground;
    unsigned int m_unkUint19;
    bool m_unkBool30;
    unsigned int m_unkUint20;
    bool m_unkBool31;
};

#endif /* __GJGAMESTATE_H__ */