#ifndef __GJBASEGAMELAYER_H__
#define __GJBASEGAMELAYER_H__


#include "../includes.h"


/* -- Predefined Subclasses -- */

class TriggerEffectDelegate;

class GJBaseGameLayer: public cocos2d::CCLayer, public TriggerEffectDelegate {
public:
     ~GJBaseGameLayer();
    static GJBaseGameLayer* get();
    void activateCustomRing(RingObject* p0);
    TodoReturn activatedAudioTrigger(SFXTriggerGameObject* p0, float p1);
    TodoReturn activateEventTrigger(EventLinkTrigger* p0, std::vector<int> const& p1);
    TodoReturn activateItemCompareTrigger(ItemTriggerGameObject* p0, std::vector<int> const& p1);
    TodoReturn activateItemEditTrigger(ItemTriggerGameObject* p0);
    void activateObjectControlTrigger(ObjectControlGameObject* p0);
    TodoReturn activatePersistentItemTrigger(ItemTriggerGameObject* p0);
    void activatePlayerControlTrigger(PlayerControlGameObject* p0);
    TodoReturn activateResetTrigger(EffectGameObject* p0);
    void activateSFXEditTrigger(SFXTriggerGameObject* p0);
    void activateSFXTrigger(SFXTriggerGameObject* p0);
    TodoReturn activateSongEditTrigger(SongTriggerGameObject* p0);
    void activateSongTrigger(SongTriggerGameObject* p0);
    TodoReturn activateTimerTrigger(TimerTriggerGameObject* p0, std::vector<int> const& p1);
    TodoReturn addAreaEffect(EnterEffectObject* p0, std::vector<EnterEffectInstance>* p1, GJAreaActionType p2);
    void addCustomEnterEffect(EnterEffectObject* p0, bool p1);
    TodoReturn addGuideArt(GameObject* p0);
    void addObjectCounter(LabelGameObject* p0);
    TodoReturn addPickupTrigger(CountTriggerGameObject* p0);
    TodoReturn addPoints(int p0);
    void addProximityVolumeEffect(int p0, int p1, SFXTriggerGameObject* p2);
    TodoReturn addRemapTargets(std::set<int>& p0);
    void addToGroupParents(GameObject* p0);
    void addToGroups(GameObject* p0, bool p1);
    TodoReturn addToObjectsToShow(GameObject* p0);
    TodoReturn addUIObject(GameObject* p0);
    void animateInDualGroundNew(GameObject* p0, float p1, bool p2, float p3);
    TodoReturn animateInGroundNew(bool p0, float p1, bool p2);
    void animateOutGroundNew(bool p0);
    TodoReturn animatePortalY(float p0, float p1, float p2, float p3);
    TodoReturn applyLevelSettings(GameObject* p0);
    TodoReturn applyRemap(EffectGameObject* p0, std::vector<int> const& p1, std::unordered_map<int, int>& p2);
    void applySFXEditTrigger(int p0, int p1, SFXTriggerGameObject* p2);
    void applyShake(cocos2d::CCPoint& p0);
    void assignNewStickyGroups(cocos2d::CCArray* p0);
    TodoReturn asyncBGLoaded(int p0);
    TodoReturn asyncGLoaded(int p0);
    TodoReturn asyncMGLoaded(int p0);
    TodoReturn atlasValue(int p0);
    void bumpPlayer(PlayerObject* p0, EffectGameObject* p1);
    TodoReturn buttonIDToButton(int p0);
    TodoReturn calculateColorGroups();
    TodoReturn cameraMoveX(float p0, float p1, float p2, bool p3);
    TodoReturn cameraMoveY(float p0, float p1, float p2, bool p3);
    bool canBeActivatedByPlayer(PlayerObject* p0, EffectGameObject* p1);
    TodoReturn canProcessSFX(SFXTriggerState& p0, std::unordered_map<int, int>& p1, std::unordered_map<int, float>& p2, std::vector<SFXTriggerState>& p3);
    TodoReturn canTouchObject(GameObject* p0);
    TodoReturn checkCameraLimitAfterTeleport(PlayerObject* p0, float p1);
    TodoReturn checkCollision(int p0, int p1);
    TodoReturn checkCollisionBlocks(EffectGameObject* p0, std::vector<EffectGameObject*>* p1, int p2);
    int checkCollisions(PlayerObject* p0, float p1, bool p2);
    TodoReturn checkRepellPlayer();
    TodoReturn checkSpawnObjects();
    TodoReturn claimMoveAction(int p0, bool p1);
    TodoReturn claimParticle(std::string p0, int p1);
    TodoReturn claimRotationAction(int p0, int p1, float& p2, float& p3, bool p4, bool p5);
    TodoReturn clearActivatedAudioTriggers();
    TodoReturn clearPickedUpItems();
    TodoReturn collectedObject(EffectGameObject* p0);
    void collisionCheckObjects(PlayerObject* p0, std::vector<GameObject*>* p1, int p2, float p3);
    TodoReturn controlAdvancedFollowCommand(AdvancedFollowTriggerObject* p0, int p1, GJActionCommand p2);
    TodoReturn controlAreaEffect(EnterEffectObject* p0, std::vector<EnterEffectInstance>* p1, GJActionCommand p2);
    TodoReturn controlAreaEffectWithID(int p0, int p1, GJActionCommand p2);
    TodoReturn controlDynamicCommand(EffectGameObject* p0, int p1, std::vector<DynamicObjectAction>& p2, GJActionCommand p3);
    TodoReturn controlDynamicMoveCommand(EffectGameObject* p0, int p1, GJActionCommand p2);
    TodoReturn controlDynamicRotateCommand(EffectGameObject* p0, int p1, GJActionCommand p2);
    TodoReturn controlEventLink(int p0, int p1, GJActionCommand p2);
    TodoReturn controlGradientTrigger(GradientTriggerObject* p0, GJActionCommand p1);
    TodoReturn controlTriggersInGroup(int p0, GJActionCommand p1);
    TodoReturn controlTriggersWithControlID(int p0, GJActionCommand p1);
    TodoReturn convertToClosestDirection(float p0, float p1);
    void createBackground(int p0);
    void createGroundLayer(int p0, int p1);
    void createMiddleground(int p0);
    TodoReturn createNewKeyframeAnim();
    TodoReturn createParticle(int p0, char const* p1, int p2, cocos2d::tCCPositionType p3);
    TodoReturn createPlayer();
    TodoReturn createPlayerCollisionBlock();
    TodoReturn createTextLayers();
    TodoReturn damagingObjectsInRect(cocos2d::CCRect p0, bool p1);
    void destroyObject(GameObject* p0);
    TodoReturn enterDualMode(GameObject* p0, bool p1);
    TodoReturn exitStaticCamera(bool p0, bool p1, float p2, int p3, float p4, bool p5, float p6, bool p7);
    TodoReturn flipFinished();
    TodoReturn flipGravity(PlayerObject* p0, bool p1, bool p2);
    TodoReturn flipObjects();
    TodoReturn gameEventToString(GJGameEvent p0);
    void gameEventTriggered(GJGameEvent p0, int p1, int p2);
    TodoReturn generateEnterEasingBuffer(int p0, float p1);
    TodoReturn generateEnterEasingBuffers(EnterEffectObject* p0);
    TodoReturn generatePickupAnimRandVal(GameObject* p0, float& p1, float& p2);
    TodoReturn generateSpawnRemap();
    TodoReturn generateTargetGroups();
    TodoReturn generateVisibilityGroups();
    TodoReturn getActiveOrderSpawnObjects();
    TodoReturn getAreaObjectValue(EnterEffectInstance* p0, GameObject* p1, cocos2d::CCPoint& p2, bool& p3);
    TodoReturn getBumpMod(PlayerObject* p0, int p1);
    TodoReturn getCameraEdgeValue(int p0);
    TodoReturn getCapacityString();
    TodoReturn getCenterGroupObject(int p0, int p1);
    TodoReturn getCustomEnterEffects(int p0, bool p1);
    TodoReturn getEasedAreaValue(GameObject* p0, EnterEffectInstance* p1, float p2, bool p3, int p4);
    TodoReturn getEnterEasingKey(int p0, float p1);
    TodoReturn getEnterEasingValue(float p0, int p1, float p2, int p3);
    TodoReturn getFollowSpeedVal(GameObject* p0, int p1, int p2, float p3, float p4);
    float getGroundHeight(PlayerObject* p0, int p1);
    TodoReturn getGroundHeightForMode(int p0);
    TodoReturn getGroup(int p0);
    TodoReturn getGroupParent(int p0);
    TodoReturn getGroupParentsString(GameObject* p0);
    TodoReturn getItemValue(int p0, int p1);
    TodoReturn getMaxPortalY();
    TodoReturn getMinDistance(cocos2d::CCPoint p0, cocos2d::CCArray* p1, float p2, int p3);
    TodoReturn getMinPortalY();
    float getModifiedDelta(float p0);
    TodoReturn getMoveTargetDelta(EffectGameObject* p0, bool p1);
    TodoReturn getOptimizedGroup(int p0);
    TodoReturn getOtherPlayer(PlayerObject* p0);
    TodoReturn getParticleKey(int p0, char const* p1, int p2, cocos2d::tCCPositionType p3);
    TodoReturn getParticleKey2(std::string p0);
    TodoReturn getPlayerButtonID(int p0, bool p1);
    TodoReturn getPlayTimerFullSeconds();
    TodoReturn getPlayTimerMilli();
    TeleportPortalObject* getPortalTarget(TeleportPortalObject* p0);
    cocos2d::CCPoint getPortalTargetPos(TeleportPortalObject* p0, GameObject* p1, PlayerObject* p2);
    TodoReturn getRecordString();
    TodoReturn getRotateCommandTargets(EnhancedTriggerObject* p0, GameObject*& p1, GameObject*& p2, GameObject*& p3);
    TodoReturn getSavedPosition(int p0, float p1);
    TodoReturn getScaledGroundHeight(float p0);
    TodoReturn getSingleGroupObject(int p0);
    TodoReturn getSpecialKey(int p0, bool p1, bool p2);
    TodoReturn getStaticGroup(int p0);
    TodoReturn getStickyGroup(int p0);
    TodoReturn getTargetFlyCameraY(GameObject* p0);
    TodoReturn getTargetGroup(int p0, int p1);
    TodoReturn getTargetGroupOrigin(int p0, int p1);
    TodoReturn gravBumpPlayer(PlayerObject* p0, EffectGameObject* p1);
    void groupStickyObjects(cocos2d::CCArray* p0);
    void handleButton(bool down, int button, bool isPlayer1);
    TodoReturn hasItem(int p0);
    bool hasUniqueCoin(EffectGameObject* p0);
    TodoReturn increaseBatchNodeCapacity();
    bool isFlipping();
    bool isPlayer2Button(int p0);
    TodoReturn lightningFlash(cocos2d::CCPoint p0, cocos2d::ccColor3B p1);
    TodoReturn lightningFlash(cocos2d::CCPoint p0, cocos2d::CCPoint p1, cocos2d::ccColor3B p2, float p3, float p4, int p5, bool p6, float p7);
    TodoReturn loadGroupParentsFromString(GameObject* p0, std::string p1);
    void loadLevelSettings();
    TodoReturn loadStartPosObject();
    TodoReturn loadUpToPosition(float p0, int p1, int p2);
    TodoReturn maxZOrderForShaderZ(int p0);
    TodoReturn minZOrderForShaderZ(int p0);
    TodoReturn modifyGroupPhysics(AdvancedFollowEditObject* p0, cocos2d::CCArray* p1);
    TodoReturn modifyObjectPhysics(AdvancedFollowEditObject* p0, GameObjectPhysics& p1);
    TodoReturn moveAreaObject(GameObject* p0, float p1, float p2);
    TodoReturn moveCameraToPos(cocos2d::CCPoint p0);
    void moveObject(GameObject* p0, double p1, double p2, bool p3);
    void moveObjects(cocos2d::CCArray* p0, double p1, double p2, bool p3);
    void moveObjectsSilent(int p0, double p1, double p2);
    TodoReturn objectIntersectsCircle(GameObject* p0, GameObject* p1);
    GJGameEvent objectTypeToGameEvent(int p0);
    TodoReturn optimizeMoveGroups();
    TodoReturn orderSpawnObjects();
    TodoReturn parentForZLayer(int p0, bool p1, int p2, int p3);
    void pauseAudio();
    TodoReturn performMathOperation(double p0, double p1, int p2);
    TodoReturn performMathRounding(double p0, int p1);
    void pickupItem(EffectGameObject* p0);
    TodoReturn playAnimationCommand(int p0, int p1);
    TodoReturn playerCircleCollision(PlayerObject* p0, GameObject* p1);
    TodoReturn playerIntersectsCircle(PlayerObject* p0, GameObject* p1);
    TodoReturn playerTouchedObject(PlayerObject* p0, GameObject* p1);
    TodoReturn playerTouchedRing(PlayerObject* p0, RingObject* p1);
    TodoReturn playerTouchedTrigger(PlayerObject* p0, EffectGameObject* p1);
    TodoReturn playerWasTouchingObject(PlayerObject* p0, GameObject* p1);
    void playerWillSwitchMode(PlayerObject* p0, GameObject* p1);
    TodoReturn playExitDualEffect(PlayerObject* p0);
    TodoReturn playFlashEffect(float p0, int p1, float p2);
    TodoReturn playKeyframeAnimation(KeyframeAnimTriggerObject* p0, std::vector<int> const& p1);
    TodoReturn playSpeedParticle(float p0);
    TodoReturn positionForShaderTarget(int p0);
    TodoReturn positionUIObjects();
    TodoReturn prepareSavePositionObjects();
    TodoReturn prepareTransformParent(bool p0);
    TodoReturn preResumeGame();
    TodoReturn preUpdateVisibility(float p0);
    TodoReturn processActivatedAudioTriggers(float p0);
    TodoReturn processAdvancedFollowAction(AdvancedFollowInstance& p0, bool p1, float p2);
    TodoReturn processAdvancedFollowActions(float p0);
    TodoReturn processAreaActions(float p0, bool p1);
    TodoReturn processAreaEffects(std::vector<EnterEffectInstance>* p0, GJAreaActionType p1, float p2, bool p3);
    TodoReturn processAreaFadeGroupAction(cocos2d::CCArray* p0, EnterEffectInstance* p1, cocos2d::CCPoint p2, bool p3);
    TodoReturn processAreaMoveGroupAction(cocos2d::CCArray* p0, EnterEffectInstance* p1, cocos2d::CCPoint p2, int p3, int p4, int p5, int p6, int p7, bool p8, bool p9);
    TodoReturn processAreaRotateGroupAction(cocos2d::CCArray* p0, EnterEffectInstance* p1, cocos2d::CCPoint p2, int p3, int p4, int p5, int p6, int p7, bool p8, bool p9);
    TodoReturn processAreaTintGroupAction(cocos2d::CCArray* p0, EnterEffectInstance* p1, cocos2d::CCPoint p2, bool p3);
    TodoReturn processAreaTransformGroupAction(cocos2d::CCArray* p0, EnterEffectInstance* p1, cocos2d::CCPoint p2, int p3, int p4, int p5, int p6, int p7, bool p8, bool p9);
    TodoReturn processAreaVisualActions(float p0);
    TodoReturn processCameraObject(GameObject* p0, PlayerObject* p1);
    void processCommands(float p0);
    TodoReturn processDynamicObjectActions(int p0, float p1);
    TodoReturn processFollowActions();
    TodoReturn processItems();
    TodoReturn processMoveActions();
    TodoReturn processMoveActionsStep(float p0, bool p1);
    TodoReturn processOptionsTrigger(GameOptionsTrigger* p0);
    TodoReturn processPlayerFollowActions(float p0);
    TodoReturn processQueuedAudioTriggers();
    TodoReturn processQueuedButtons();
    TodoReturn processRotationActions();
    TodoReturn processSFXObjects();
    TodoReturn processSFXState(SFXTriggerState* p0, SFXTriggerState* p1, int p2, float p3);
    TodoReturn processSongState(int p0, float p1, float p2, int p3, float p4, float p5, std::vector<SongTriggerState>* p6);
    TodoReturn processStateObjects();
    TodoReturn processTransformActions(bool p0);
    void queueButton(int p0, bool p1, bool p2);
    TodoReturn reAddToStickyGroup(GameObject* p0);
    TodoReturn recordAction(int p0, bool p1, bool p2);
    TodoReturn rectIntersectsCircle(cocos2d::CCRect p0, cocos2d::CCPoint p1, float p2);
    TodoReturn refreshCounterLabels();
    TodoReturn refreshKeyframeAnims();
    TodoReturn regenerateEnterEasingBuffers();
    TodoReturn registerSpawnRemap(std::vector<ChanceObject>& p0);
    TodoReturn registerStateObject(EffectGameObject* p0);
    TodoReturn removeBackground();
    TodoReturn removeCustomEnterEffects(int p0, bool p1);
    void removeFromGroupParents(GameObject* p0);
    void removeFromGroups(GameObject* p0);
    TodoReturn removeFromStickyGroup(GameObject* p0);
    TodoReturn removeGroundLayer();
    TodoReturn removeGroupParent(int p0);
    TodoReturn removeKeyframe(KeyframeGameObject* p0);
    TodoReturn removeMiddleground();
    void removeObjectFromSection(GameObject* p0);
    TodoReturn removePlayer2();
    TodoReturn removeTemporaryParticles();
    TodoReturn reorderObjectSection(GameObject* p0);
    TodoReturn reparentObject(cocos2d::CCNode* p0, cocos2d::CCNode* p1);
    void resetActiveEnterEffects();
    TodoReturn resetAreaObjectValues(GameObject* p0, bool p1);
    TodoReturn resetAudio();
    void resetCamera();
    void resetGradientLayers();
    TodoReturn resetGroupCounters(bool p0);
    void resetLevelVariables();
    TodoReturn resetMoveOptimizedValue();
    void resetPlayer();
    void resetSongTriggerValues();
    TodoReturn resetSpawnChannelIndex();
    TodoReturn resetStaticCamera(bool p0, bool p1);
    TodoReturn resetStoppedAreaObjects();
    TodoReturn restoreAllUIObjects();
    TodoReturn restoreDefaultGameplayOffsetX();
    TodoReturn restoreDefaultGameplayOffsetY();
    TodoReturn restoreRemap(EffectGameObject* p0, std::unordered_map<int, int>& p1);
    TodoReturn resumeAudio();
    TodoReturn rotateAreaObjects(GameObject* p0, cocos2d::CCArray* p1, float p2, bool p3);
    TodoReturn rotateObject(GameObject* p0, float p1);
    void rotateObjects(cocos2d::CCArray* p0, float p1, cocos2d::CCPoint p2, cocos2d::CCPoint p3, bool p4, bool p5);
    void setGroupParent(GameObject* p0, int p1);
    void setStartPosObject(StartPosObject* p0);
    void setupLayers();
    TodoReturn setupLevelStart(LevelSettingsObject* p0);
    void setupReplay(std::string p0);
    TodoReturn shakeCamera(float p0, float p1, float p2);
    TodoReturn shouldExitHackedLevel();
    TodoReturn sortAllGroupsX();
    TodoReturn sortGroups();
    TodoReturn sortSectionVector();
    TodoReturn sortStickyGroups();
    void spawnGroupTriggered(int groupID, float p1, bool p2, std::vector<int> const& p3, int p4, int p5);
    TodoReturn spawnObjectsInOrder(cocos2d::CCArray* p0, double p1, std::vector<int> const& p2, int p3, int p4);
    TodoReturn spawnParticle(char const* p0, int p1, cocos2d::tCCPositionType p2, cocos2d::CCPoint p3);
    TodoReturn spawnParticleTrigger(int p0, cocos2d::CCPoint p1, float p2, float p3);
    TodoReturn spawnParticleTrigger(SpawnParticleGameObject* p0);
    TodoReturn spawnPlayer2();
    TodoReturn speedForShaderTarget(int p0);
    TodoReturn staticObjectsInRect(cocos2d::CCRect p0, bool p1);
    TodoReturn stopAllGroundActions();
    TodoReturn stopCameraShake();
    TodoReturn stopCustomEnterEffect(EnterEffectObject* p0, bool p1);
    TodoReturn stopCustomEnterEffect(EnterEffectObject* p0);
    TodoReturn stopSFXTrigger(SFXTriggerGameObject* p0);
    TodoReturn swapBackground(int p0);
    TodoReturn swapGround(int p0);
    TodoReturn swapMiddleground(int p0);
    void switchToFlyMode(PlayerObject* p0, GameObject* p1, bool p2, int p3);
    void switchToRobotMode(PlayerObject* p0, GameObject* p1, bool p2);
    void switchToRollMode(PlayerObject* p0, GameObject* p1, bool p2);
    void switchToSpiderMode(PlayerObject* p0, GameObject* p1, bool p2);
    TodoReturn syncBGTextures();
    void teleportPlayer(TeleportPortalObject* p0, PlayerObject* p1);
    TodoReturn testInstantCountTrigger(int p0, int p1, int p2, bool p3, int p4, std::vector<int> const& p5, int p6, int p7);
    void toggleAudioVisualizer(bool p0);
    void toggleDualMode(GameObject* p0, bool p1, PlayerObject* p2, bool p3);
    void toggleFlipped(bool p0, bool p1);
    TodoReturn toggleGroup(int p0, bool p1);
    TodoReturn toggleLockPlayer(bool p0, bool p1);
    TodoReturn togglePlayerStreakBlend(bool p0);
    void togglePlayerVisibility(bool p0, bool p1);
    TodoReturn togglePlayerVisibility(bool p0);
    TodoReturn transformAreaObjects(GameObject* p0, cocos2d::CCArray* p1, float p2, float p3, bool p4);
    TodoReturn triggerAdvancedFollowCommand(AdvancedFollowTriggerObject* p0);
    TodoReturn triggerAdvancedFollowEditCommand(AdvancedFollowEditObject* p0);
    TodoReturn triggerAreaEffect(EnterEffectObject* p0);
    TodoReturn triggerAreaEffectAnimation(EnterEffectObject* p0);
    TodoReturn triggerDynamicMoveCommand(EffectGameObject* p0);
    TodoReturn triggerDynamicRotateCommand(EnhancedTriggerObject* p0);
    TodoReturn triggerGradientCommand(GradientTriggerObject* p0);
    TodoReturn triggerGravityChange(EffectGameObject* p0, int p1);
    TodoReturn triggerMoveCommand(EffectGameObject* p0);
    TodoReturn triggerRotateCommand(EnhancedTriggerObject* p0);
    bool triggerShaderCommand(ShaderGameObject* p0);
    TodoReturn triggerTransformCommand(TransformTriggerGameObject* p0);
    TodoReturn tryGetGroupParent(int p0);
    TodoReturn tryGetMainObject(int p0);
    TodoReturn tryGetObject(int p0);
    TodoReturn tryResumeAudio();
    TodoReturn unclaimParticle(char const* p0, cocos2d::CCParticleSystemQuad* p1);
    void ungroupStickyObjects(cocos2d::CCArray* p0);
    TodoReturn unlinkAllEvents();
    TodoReturn updateActiveEnterEffect(EnterEffectObject* p0);
    TodoReturn updateAllObjectSection();
    TodoReturn updateAreaObjectLastValues(GameObject* p0);
    TodoReturn updateAudioVisualizer();
    TodoReturn updateBGArtSpeed(float p0, float p1);
    void updateCamera(float p0);
    TodoReturn updateCameraBGArt(cocos2d::CCPoint p0, float p1);
    TodoReturn updateCameraEdge(int p0, int p1);
    void updateCameraMode(EffectGameObject* p0, bool p1);
    TodoReturn updateCameraOffsetX(float p0, float p1, int p2, float p3, int p4, int p5);
    TodoReturn updateCameraOffsetY(float p0, float p1, int p2, float p3, int p4, int p5);
    TodoReturn updateCollisionBlocks();
    void updateCounters(int p0, int p1);
    void updateDualGround(PlayerObject* p0, int p1, bool p2, float p3);
    TodoReturn updateEnterEffects(float p0);
    TodoReturn updateExtendedCollision(GameObject* p0, bool p1);
    TodoReturn updateExtraGameLayers();
    TodoReturn updateGameplayOffsetX(int p0, bool p1);
    TodoReturn updateGameplayOffsetY(int p0, bool p1);
    TodoReturn updateGradientLayers();
    TodoReturn updateGroundShadows();
    TodoReturn updateGuideArt();
    TodoReturn updateInternalCamOffsetX(float p0, float p1, float p2);
    TodoReturn updateInternalCamOffsetY(float p0, float p1, float p2);
    TodoReturn updateKeyframeOrder(int p0);
    TodoReturn updateLayerCapacity(std::string p0);
    TodoReturn updateLegacyLayerCapacity(int p0, int p1, int p2, int p3);
    TodoReturn updateLevelColors();
    void updateMaxGameplayY();
    TodoReturn updateMGArtSpeed(float p0, float p1);
    void updateMGOffsetY(float p0, float p1, int p2, float p3, int p4, int p5);
    TodoReturn updateOBB2(cocos2d::CCRect p0);
    TodoReturn updateParticles(float p0);
    TodoReturn updatePlatformerTime();
    TodoReturn updatePlayerCollisionBlocks();
    TodoReturn updateProximityVolumeEffects();
    TodoReturn updateQueuedLabels();
    TodoReturn updateReplay();
    TodoReturn updateSavePositionObjects();
    TodoReturn updateShaderLayer(float p0);
    TodoReturn updateSpecialGroupData();
    TodoReturn updateSpecialLabels();
    void updateStaticCameraPos(cocos2d::CCPoint p0, bool p1, bool p2, bool p3, float p4, int p5, float p6);
    TodoReturn updateStaticCameraPosToGroup(int p0, bool p1, bool p2, bool p3, float p4, float p5, int p6, float p7, bool p8, float p9);
    TodoReturn updateTimeMod(float p0, bool p1, bool p2);
    TodoReturn updateTimerLabels();
    void updateZoom(float p0, float p1, int p2, float p3, int p4, int p5);
    TodoReturn visitWithColorFlash();
    TodoReturn volumeForProximityEffect(SFXTriggerInstance& p0);
    virtual void update(float p0);
    virtual bool init();
    virtual void visit();
    virtual void postUpdate(float p0);
    virtual TodoReturn checkForEnd();
    virtual TodoReturn testTime();
    virtual void updateVerifyDamage();
    virtual void updateAttemptTime(float p0);
    virtual void updateVisibility(float p0);
    virtual TodoReturn playerTookDamage(PlayerObject* p0);
    virtual TodoReturn opacityForObject(GameObject* p0);
    virtual TodoReturn addToSpeedObjects(EffectGameObject* p0);
    virtual void objectsCollided(int p0, int p1);
    virtual void updateColor(cocos2d::ccColor3B& p0, float p1, int p2, bool p3, float p4, cocos2d::ccHSVValue& p5, int p6, bool p7, EffectGameObject* p8, int p9, int p10);
    virtual void toggleGroupTriggered(int p0, bool p1, std::vector<int> const& p2, int p3, int p4);
    virtual void spawnGroup(int p0, bool p1, double p2, std::vector<int> const& p3, int p4, int p5);
    virtual void spawnObject(GameObject* p0, double p1, std::vector<int> const& p2);
    virtual TodoReturn activateEndTrigger(int p0, bool p1, bool p2);
    virtual void activatePlatformerEndTrigger(EndTriggerGameObject* p0, std::vector<int> const& p1);
    virtual void toggleGlitter(bool p0);
    virtual void destroyPlayer(PlayerObject* p0, GameObject* p1);
    virtual void updateDebugDraw();
    virtual void addToSection(GameObject* p0);
    virtual void addToGroup(GameObject* p0, int p1, bool p2);
    virtual void removeFromGroup(GameObject* p0, int p1);
    virtual TodoReturn updateObjectSection(GameObject* p0);
    virtual TodoReturn updateDisabledObjectsLastPos(cocos2d::CCArray* p0);
    virtual TodoReturn toggleGroundVisibility(bool p0);
    virtual TodoReturn toggleMGVisibility(bool p0);
    virtual TodoReturn toggleHideAttempts(bool p0);
    virtual float timeForPos(cocos2d::CCPoint p0, int p1, int p2, bool p3, int p4);
    virtual float posForTime(float p0);
    virtual void resetSPTriggered();
    virtual TodoReturn updateScreenRotation(float p0, bool p1, bool p2, float p3, int p4, float p5, int p6, int p7);
    virtual TodoReturn reverseDirection(EffectGameObject* p0);
    virtual TodoReturn rotateGameplay(RotateGameplayGameObject* p0);
    virtual TodoReturn didRotateGameplay();
    virtual TodoReturn updateTimeWarp(float p0);
    virtual TodoReturn updateTimeWarp(GameObject* p0, float p1);
    virtual TodoReturn applyTimeWarp(float p0);
    virtual TodoReturn playGravityEffect(bool p0);
    virtual TodoReturn manualUpdateObjectColors(GameObject* p0);
    virtual TodoReturn createCustomParticle(std::string const& p0, cocos2d::ParticleStruct const& p1, int p2, bool p3);
    virtual TodoReturn claimCustomParticle(std::string const& p0, cocos2d::ParticleStruct const& p1, int p2, int p3, int p4, bool p5);
    virtual TodoReturn unclaimCustomParticle(std::string const& p0, cocos2d::CCParticleSystemQuad* p1);
    virtual TodoReturn activatedAudioTrigger(SFXTriggerGameObject* p0);
    virtual void checkpointActivated(CheckpointGameObject* p0);
    virtual TodoReturn flipArt(bool p0);
    virtual TodoReturn addKeyframe(KeyframeGameObject* p0);
    virtual void updateTimeLabel(int p0, int p1, bool p2);
    virtual TodoReturn checkSnapshot();
    virtual void toggleProgressbar();
    virtual TodoReturn toggleInfoLabel();
    virtual void removeAllCheckpoints();
    virtual TodoReturn toggleMusicInPractice();
    /* PAD */

    GJGameState m_gameState;
    GJGameLevel* m_level;
    PlaybackMode m_playbackMode;
    /* PAD */

    GJEffectManager* m_effectManager;
    /* PAD */

    PlayerObject* m_player1;
    PlayerObject* m_player2;
    LevelSettingsObject* m_levelSettings;
    cocos2d::CCArray* m_objects;
    cocos2d::CCArray* m_unknownCB0;
    cocos2d::CCArray* m_unknownCB8;
    cocos2d::CCDictionary* m_unknownCC0;
    cocos2d::CCNode* m_unknownCC8;
    std::vector<GameObject*> m_unknownCD0;
    std::vector<GameObject*> m_unknownCE8;
    std::vector<GameObject*> m_unknownD00;
    std::vector<GameObject*> m_unknownD18;
    std::vector<GameObject*> m_unknownD30;
    std::unordered_map<int, std::vector<GameObject*>> m_unknownD48;
    std::vector<GameObject*> m_unknownD70;
    std::unordered_map<int, std::vector<GameObject*>> m_unknownD88;
    int m_unknownDB0;
    int m_unknownDB8;
    int m_unknownDBC;
    int m_unknownDC0;
    int m_unknownDC4;
    int m_unknownDC8;
    int m_unknownDCC;
    int m_unknownDD0;
    int m_unknownDD4;
    cocos2d::CCDictionary* m_groupDict;
    cocos2d::CCDictionary* m_staticGroupDict;
    cocos2d::CCDictionary* m_optimizedGroupDict;
    std::vector<cocos2d::CCArray*> m_groups;
    std::vector<cocos2d::CCArray*> m_staticGroups;
    std::vector<cocos2d::CCArray*> m_optimizedGroups;
    cocos2d::CCDictionary* m_unknownE38;
    cocos2d::CCDictionary* m_unknownE40;
    cocos2d::CCDictionary* m_unknownE48;
    cocos2d::CCArray* m_unknownE50;
    std::unordered_map<int, std::pair<int, int>> m_unknownE58;
    cocos2d::CCDictionary* m_linkedGroupDict;
    int m_lastUsedLinkedID;
    cocos2d::CCNode* m_unknownE90;
    cocos2d::CCNode* m_unknownE98;
    cocos2d::CCNode* m_unknownEA0;
    cocos2d::CCLayer* m_objectLayer;
    /* PAD */

    GJGroundLayer* m_groundLayer;
    /* PAD */

    std::array<float, 2000> m_massiveFloatArray;
    /* PAD */

    int m_leftSectionIndex;
    int m_rightSectionIndex;
    int m_bottomSectionIndex;
    int m_topSectionIndex;
    /* PAD */

    bool m_isPracticeMode;
    bool m_practiceMusicSync;
    float m_loadingProgress;
    cocos2d::CCNode* m_unk2a84;
    int m_unk2a88;
    float m_unk2a8c;
    int m_unk2a90;
    int m_unk2a94;
    int m_unk2a98;
    cocos2d::CCDictionary* m_unk2a9c;
    float m_levelLength;
    int m_unk2aa4;
    EndPortalObject* m_endPortal;
    bool m_isTestMode;
    /* PAD */

    bool m_started;
    /* PAD */

    std::vector<PlayerButtonCommand> m_queuedButtons;
    /* PAD */

    UILayer* m_uiLayer;
    /* PAD */

    std::vector<std::vector<std::vector<GameObject*>*>*> m_sections;
    /* PAD */

    std::vector<std::vector<int>*> m_nonEffectObjectsPerSection;
    /* PAD */

    GJGameLoadingLayer* m_loadingLayer;
    cocos2d::CCDrawNode* m_debugDrawNode;
    /* PAD */

    bool m_isDebugDrawEnabled;
};

#endif /* __GJBASEGAMELAYER_H__ */